# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=400, verbose_name='Meta-tag title')),
                ('meta_kw', models.CharField(max_length=400, verbose_name='Meta-tag keywords')),
                ('meta_desc', models.TextField(verbose_name='Meta-tag Description')),
                ('header', models.CharField(max_length=400, verbose_name='Header (tag H1)')),
                ('short_content', models.TextField(verbose_name='Short content for preview')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to=b'blog/%Y/%m/%d', verbose_name='Image')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Is moderated')),
                ('da', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('de', models.DateTimeField(auto_now=True, verbose_name='Date of last edit')),
            ],
            options={
                'ordering': ['-da'],
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
            },
        ),
    ]
