# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_moderated',
            field=models.BooleanField(default=True, verbose_name='Is moderated'),
        ),
    ]
