# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogposts', '0002_auto_20160205_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default='default slug', max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
