# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 09:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogposts', '0002_auto_20160205_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='default slug', editable=False, max_length=100, populate_from=b'header', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
