# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogposts', '0006_auto_20160301_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='django_blogposts.Tags', verbose_name='tags'),
        ),
    ]
