# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 10:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogposts', '0006_auto_20160301_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_content',
            field=ckeditor.fields.RichTextField(verbose_name='Short content for preview'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='django_blogposts.Tags', verbose_name='tags'),
        ),
    ]
