# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 11:15
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogposts', '0008_auto_20160301_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'blog/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_content',
            field=models.TextField(blank=True, null=True, verbose_name='Short content for preview'),
        ),
    ]
